import { defineConfig } from "drizzle-kit";

/**
 * drizzle-kit reads .env automatically. The auth tables in db/schema/auth.ts are
 * generated by the Better Auth CLI (`bun run db:generate-auth`); app tables live
 * in db/schema/app.ts. Both are re-exported from db/schema/index.ts.
 */
export default defineConfig({
  schema: "./db/schema/index.ts",
  out: "./db/migrations",
  dialect: "postgresql",
  dbCredentials: {
    url: process.env.DIRECT_DATABASE_URL ?? process.env.DATABASE_URL!,
  },
  verbose: true,
  strict: true,
});
