/**
 * Starter configuration — the switchboard for generated projects.
 *
 * This file is generated by `bun run create`. It contains no secrets.
 * Add or remove add-ons here when you want UI, routes, docs, and integrations
 * to agree about what this project includes.
 */
export const starterConfig = {
  appName: "Next Starter",

  /** "single" bills each user directly; "multi" enables organizations + per-seat billing. */
  tenancy: "multi",

  scaffold: {
    source: "next-starter",
    profile: "client-portal",
    websiteSpec: "https://specification.website/checklist",
    addons: [
      "seo",
      "accessibility",
      "security",
      "performance",
      "privacy",
      "resilience",
      "agent-readiness",
      "neon",
      "better-auth",
      "audit",
      "oauth",
      "passkeys",
      "resend",
      "upstash",
    ],
  },

  integrations: {
    oauth: { google: true, github: true },
    billing: false, // Stripe
    email: true, // Resend
    rateLimit: true, // Upstash
    twoFactor: true,
    passkeys: true,
    magicLink: true,
    ai: {
      enabled: false,
      chat: false,
      structuredOutput: false,
      persistHistory: false,
    },
  },

  capabilities: {
    audit: true,
  },
} as const;

export type StarterConfig = typeof starterConfig;
