import {
  ADDONS,
  type AddonDefinition,
  type AddonId,
  DEFAULT_ADDON_IDS,
  FULL_STACK_ADDON_IDS,
  getAddon,
  WEBSITE_SPEC_CATEGORIES,
  WEBSITE_SPEC_SOURCE,
} from "./addons";
import { getProfile, type ProfileId } from "./profiles";
import { WEBSITE_SPEC_ITEM_COUNT } from "./website-spec";
import { websiteSpecComplianceSummary } from "./website-spec-compliance";

export type ScaffoldOptions = {
  appName: string;
  addons: AddonId[];
  includeDefaults?: boolean;
  profile?: ProfileId | null;
  tenancy?: "single" | "multi";
};

export type ResolvedScaffold = {
  appName: string;
  addonIds: AddonId[];
  addons: AddonDefinition[];
  env: AddonDefinition["env"];
  profile: ProfileId | null;
  tenancy: "single" | "multi";
};

export function parseAddonIds(value: string): AddonId[] {
  if (value.trim() === "all") return [...FULL_STACK_ADDON_IDS];
  if (!value.trim()) return [];

  return value
    .split(",")
    .map((part) => part.trim())
    .filter(Boolean)
    .map((id) => {
      if (!ADDONS.some((addon) => addon.id === id)) {
        throw new Error(
          `Unknown add-on "${id}". Run with --list to see available add-ons.`,
        );
      }
      return id as AddonId;
    });
}

export function resolveAddonIds(
  requested: readonly AddonId[],
  includeDefaults = true,
): AddonId[] {
  const ordered = new Set<AddonId>();

  function visit(id: AddonId) {
    const addon = getAddon(id);
    for (const dependency of addon.dependencies) {
      visit(dependency);
    }
    ordered.add(id);
  }

  if (includeDefaults) {
    for (const id of DEFAULT_ADDON_IDS) visit(id);
  }

  for (const id of requested) visit(id);

  return ADDONS.map((addon) => addon.id).filter((id) => ordered.has(id));
}

export function resolveScaffold(options: ScaffoldOptions): ResolvedScaffold {
  const profile = options.profile ? getProfile(options.profile) : null;
  const requestedAddons = [...(profile?.addons ?? []), ...options.addons];
  const includeDefaults =
    options.includeDefaults ?? profile?.includeDefaults ?? true;
  const addonIds = resolveAddonIds(requestedAddons, includeDefaults);
  const addons = addonIds.map(getAddon);
  const env = addons.flatMap((addon) => addon.env);

  return {
    appName: options.appName,
    addonIds,
    addons,
    env: env.filter(
      (variable, index) =>
        env.findIndex((candidate) => candidate.name === variable.name) ===
        index,
    ),
    profile: profile?.id ?? null,
    tenancy: options.tenancy ?? profile?.tenancy ?? "multi",
  };
}

export function renderStarterConfig(options: ScaffoldOptions): string {
  const resolved = resolveScaffold(options);
  const enabled = new Set(resolved.addonIds);
  const addonLines = resolved.addonIds.map((id) => `      "${id}",`).join("\n");

  return `/**
 * Starter configuration — the switchboard for generated projects.
 *
 * This file is generated by \`bun run create\`. It contains no secrets.
 * Add or remove add-ons here when you want UI, routes, docs, and integrations
 * to agree about what this project includes.
 */
export const starterConfig = {
  appName: ${JSON.stringify(resolved.appName)},

  /** "single" bills each user directly; "multi" enables organizations + per-seat billing. */
  tenancy: ${JSON.stringify(resolved.tenancy)},

  scaffold: {
    source: "next-starter",
    profile: ${JSON.stringify(resolved.profile)},
    websiteSpec: ${JSON.stringify(WEBSITE_SPEC_SOURCE)},
    addons: [
${addonLines}
    ],
  },

  integrations: {
    oauth: { google: ${enabled.has("oauth")}, github: ${enabled.has("oauth")} },
    billing: ${enabled.has("stripe")}, // Stripe
    email: ${enabled.has("resend")}, // Resend
    rateLimit: ${enabled.has("upstash")}, // Upstash
    twoFactor: ${enabled.has("better-auth")},
    passkeys: ${enabled.has("passkeys")},
    magicLink: ${enabled.has("better-auth")},
    ai: {
      enabled: ${enabled.has("ai")},
      chat: ${enabled.has("ai")},
      structuredOutput: ${enabled.has("ai")},
      persistHistory: ${enabled.has("ai") && enabled.has("neon")},
    },
  },

  capabilities: {
    audit: ${enabled.has("audit")},
  },
} as const;

export type StarterConfig = typeof starterConfig;
`;
}

export function renderEnvExample(options: ScaffoldOptions): string {
  const resolved = resolveScaffold(options);
  const lines = [
    "# ---------------------------------------------------------------------------",
    "# Copy to `.env` for local development. Never commit real secrets.",
    "# This file is generated from selected scaffold add-ons.",
    "# ---------------------------------------------------------------------------",
    "",
    "# --- App ---",
    "NEXT_PUBLIC_APP_URL=http://localhost:3450",
    "DEPLOYMENT_ENV=development",
    "# Required in production; previews must use a different origin.",
    "CANONICAL_APP_URL=",
    "",
  ];

  if (resolved.env.length === 0) {
    lines.push(
      "# No service credentials are required by the selected add-ons.",
      "",
    );
    return `${lines.join("\n")}\n`;
  }

  for (const addon of resolved.addons) {
    if (addon.env.length === 0) continue;
    lines.push(`# --- ${addon.label} ---`);
    for (const variable of addon.env) {
      lines.push(
        `# ${variable.required ? "Required" : "Optional"}: ${variable.description}`,
      );
      if (variable.example) lines.push(`# Example: ${variable.example}`);
      lines.push(`${variable.name}=`);
    }
    lines.push("");
  }

  return `${lines.join("\n")}\n`;
}

export function renderScaffoldManifest(options: ScaffoldOptions): string {
  const resolved = resolveScaffold(options);
  const enabled = new Set(resolved.addonIds);
  const disabledAddons = ADDONS.filter((addon) => !enabled.has(addon.id));
  const selectedFiles = [
    ...new Set(resolved.addons.flatMap((addon) => addon.files)),
  ].sort();
  const disabledFilePatterns = [
    ...new Set(disabledAddons.flatMap((addon) => addon.files)),
  ].sort();

  return `${JSON.stringify(
    {
      schemaVersion: 1,
      appName: resolved.appName,
      source: "next-starter",
      profile: resolved.profile,
      tenancy: resolved.tenancy,
      addons: {
        selected: resolved.addonIds,
        disabled: disabledAddons.map((addon) => addon.id),
        selectedFiles,
        disabledFilePatterns,
      },
      env: resolved.env.map((variable) => ({
        name: variable.name,
        required: variable.required,
        description: variable.description,
      })),
      websiteSpec: websiteSpecComplianceSummary(),
      pruning: {
        mode: "config-gated",
        note: "Generated projects are configured from selected add-ons. This manifest lists selected and disabled file ownership so physical pruning can be audited or applied by downstream tooling.",
      },
    },
    null,
    2,
  )}\n`;
}

export function renderScaffoldReadme(options: ScaffoldOptions): string {
  const resolved = resolveScaffold(options);
  const addonList = resolved.addons
    .map((addon) => `- **${addon.label}**: ${addon.summary}`)
    .join("\n");
  const specList = WEBSITE_SPEC_CATEGORIES.map(
    (category) => `- **${category.label}**: ${category.summary}`,
  ).join("\n");

  return `# ${resolved.appName}

Generated from the Next Starter scaffold.

## Product profile

${resolved.profile ? `**${getProfile(resolved.profile).label}**: ${getProfile(resolved.profile).summary}` : "Custom add-on selection."}

## Selected add-ons

${addonList}

## Website Specification baseline

This project is generated against the checklist at ${WEBSITE_SPEC_SOURCE}. The scaffold tracks all ${WEBSITE_SPEC_ITEM_COUNT} current checklist items and includes defaults for:

${specList}

The generated \`.scaffold-manifest.json\` records selected add-ons, disabled add-ons, env requirements, owned file patterns, and Website Specification coverage from the same registry used by the CLI.

## Local development

\`\`\`bash
bun install
cp .env.example .env
bun run dev
\`\`\`

Before starting, fill in DATABASE_URL and BETTER_AUTH_SECRET in .env, then run
\`bun run db:migrate\`. Optional providers need their own credentials.

Open http://localhost:3450. Run \`bun run validate:full\` to check this project.
See [agent workflows](docs/agent-workflows.md) for optional tooling and research.
The application retains config-gated dependencies; excluded features are not physically pruned.
`;
}

export function renderAddonList(): string {
  const rows = ADDONS.map((addon) => {
    const suffix =
      addon.dependencies.length > 0
        ? ` (depends on ${addon.dependencies.join(", ")})`
        : "";
    return `- ${addon.id}: ${addon.label}${suffix}`;
  });
  return rows.join("\n");
}
